"""Phase 7 — ``nnUNetTrainerGoATv2``: a warm-started, domain-randomised GoAT trainer.

This is a **second, independent** trainer that lives alongside :mod:`brats2026.nnunet.trainer`.
It exists because hyperparameter tuning has saturated (submission 1 already sits at
top-leaderboard parity; successive runs move the score by ~1e-2 to 1e-3), while Task 3 is scored
on *generalisation* — and two of the five cohorts (SSA, PED) have **no training data at all**
(``docs/synapse_wiki_raw/Task3_data.md``). The remaining lever is augmentation, not tuning.

v2 therefore

- **warm-starts** from an already-converged GoAT run's checkpoint (``init_weights_from``), so a
  fold that v1 has finished can be improved without paying for training from scratch again, and
- inherits **nnU-Net's own aggressive-augmentation variant** ``nnUNetTrainerDA5`` as its base
  class, rather than hand-tuning probabilities on top of the stock pipeline.

The DA5 decision is deliberate and was a correction: DA5 already ships
``BrightnessGradientAdditiveTransform`` and ``LocalGammaTransform`` at p=0.3, which is
spatially-varying intensity corruption — the same intent as the bias field this module also
implements, but validated in DKFZ's own challenge entries. Building on it means the augmentation
is DKFZ's, and only the warm start, the config gate and the retuning hooks are ours.

**Why a separate module and not new hooks on v1.** :data:`brats2026.config.TRAIN_HOOK_KEYS` is a
verbatim alias of :data:`brats2026.nnunet.trainer.SPECIALIST_HOOKS`, so adding one hook there
would immediately make the *in-flight* ``configs/train.yaml`` invalid (the new key would read as
unset) and the running job would refuse to restart. v1 is therefore strictly untouched. nnU-Net
also derives its output directory from ``<trainer>__<plans>__<configuration>``, so a distinct
class name keeps v2's results from colliding with the folds still training.

**GoAT rule compliance.** Warm-starting from *our own* GoAT-trained weights is allowed: the rule
forbids external data and weights derived from a **prior BraTS**, not resuming one of our own
runs. Nothing here initialises from an external corpus. The hook is named ``init_weights_from``
rather than ``pretrained_*`` because :data:`brats2026.compliance.PRIOR_BRATS_TOKENS` flags those
substrings, and a compliant name must not trip our own gate.

Like the rest of the package this module invents **no** numbers: every tunable is a
``# SPECIALIST:`` hook on :class:`GoATTrainerConfigV2` defaulting to ``None``. Pure functions stay
stdlib/numpy only — imported *inside* the functions — so the module and its tests load without
torch / nnU-Net (CI has neither). The concrete class is defined only when nnU-Net is importable,
mirroring :class:`brats2026.nnunet.trainer.nnUNetTrainerGoAT`.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, fields
from pathlib import Path
from typing import Optional

# nnU-Net resolves a trainer by NAME and cannot be handed a config object, so the trainer reads
# this env var (a path to a filled configs/train_v2.yaml) at initialize() time. Deliberately
# distinct from v1's BRATS_GOAT_TRAIN_CONFIG so both can be exported in the same shell.
GOAT_V2_TRAIN_CONFIG_ENV = "BRATS_GOAT_V2_TRAIN_CONFIG"

# nnU-Net discovers trainers by scanning its own package tree, so an external trainer needs a
# shim dropped in there. The filename MUST differ from v1's ``brats2026_goat.py``: overwriting it
# would swap the trainer out from under the run that is currently training.
GOAT_V2_SHIM_NAME = "brats2026_goat_v2.py"
GOAT_V2_SHIM_BODY = (
    "# Auto-generated by `brats2026 install-trainer-v2` so nnU-Net can discover the v2 trainer.\n"
    "from brats2026.nnunet.trainer_v2 import nnUNetTrainerGoATv2  # noqa: F401\n"
)

# SPECIALIST tuple-valued hooks: YAML carries them as lists; coerce to tuples when building.
_TUPLE_HOOKS: tuple[str, ...] = ("patch_size", "da_scale_range", "da_bias_field_coeff_range")

# Non-hook config keys (see SPECIALIST_HOOKS_V2 for why these are choices). They must be read
# explicitly: anything absent from the hook tuple would otherwise be dropped on the floor.
_CHOICE_KEYS: tuple[str, ...] = ("init_weights_from", "init_weights_strict")

# The knobs the specialist owns. Names mirror GoATTrainerConfigV2 fields below.
#
# Deliberately ABSENT, and why:
#   - ``init_weights_from`` / ``init_weights_strict`` are a CHOICE, not a tunable: ``None`` must
#     stay legal (= train from scratch), which assert_configured would forbid. Same treatment as
#     ``placement_mode`` in synthesis.masks and ``allow_validation_pool`` in ssl.
#   - ``domain_sampling_alpha`` (v1) is dropped: the on-disk case ids are ``BraTS-GoAT-NNNNN``, so
#     ``domains.cohort_from_case_id`` returns UNK for all 1351 cases and there is no cohort to
#     rebalance. Re-add it only once the 2026 layout (``BraTS-<COHORT>-…``) lands.
#   - v1's three ``domain_rand_*`` knobs are superseded by the finer-grained ``da_*`` set below.
SPECIALIST_HOOKS_V2: tuple[str, ...] = (
    # --- optimiser / schedule (same contract as v1) ---
    "initial_lr",
    "weight_decay",
    "num_epochs",
    "batch_size",
    "patch_size",
    "oversample_foreground_percent",
    "loss_dice_weight",
    "loss_ce_weight",
    # --- domain randomisation: probabilities OVERRIDE nnU-Net's defaults, they do not add to them
    "da_scale_range",
    "da_noise_p",
    "da_blur_p",
    "da_brightness_p",
    "da_contrast_p",
    "da_low_res_p",
    "da_gamma_p",
    # --- bias field: MRI-specific, genuinely absent from nnU-Net's default pipeline ---
    "da_bias_field_p",
    "da_bias_field_order",
    "da_bias_field_coeff_range",
)


@dataclass
class GoATTrainerConfigV2:
    """Hyperparameters for ``nnUNetTrainerGoATv2`` — every ``# SPECIALIST:`` hook, plus 2 choices.

    Defaults are ``None`` on purpose: ``None`` means "not yet decided by the specialist".
    Reference values live in the comments only, never silently applied. ``init_weights_from`` and
    ``init_weights_strict`` are choices (see :data:`SPECIALIST_HOOKS_V2`), so they are excluded
    from the hook tuple and ``None`` leaves them inert.
    """

    # --- optimiser / schedule ---
    initial_lr: Optional[float] = None            # SPECIALIST: nnU-Net default 1e-2; LOWER when warm-starting a converged model
    weight_decay: Optional[float] = None          # SPECIALIST: nnU-Net default 3e-5
    num_epochs: Optional[int] = None              # SPECIALIST: nnU-Net default 1000; a warm start needs far fewer
    batch_size: Optional[int] = None              # SPECIALIST: planner-derived; watch A10G 24GB
    patch_size: Optional[tuple[int, int, int]] = None  # SPECIALIST: planner-derived
    oversample_foreground_percent: Optional[float] = None  # SPECIALIST: nnU-Net default 0.33
    loss_dice_weight: Optional[float] = None      # SPECIALIST: region Dice weight
    loss_ce_weight: Optional[float] = None        # SPECIALIST: region BCE/CE weight

    # --- domain randomisation (override nnU-Net's default DA probabilities) ---
    da_scale_range: Optional[tuple[float, float]] = None  # SPECIALIST: scale aug range; widen for small paediatric brains / sub-cm mets
    da_noise_p: Optional[float] = None            # SPECIALIST: additive Gaussian-noise probability
    da_blur_p: Optional[float] = None             # SPECIALIST: Gaussian-blur probability
    da_brightness_p: Optional[float] = None       # SPECIALIST: multiplicative-brightness probability
    da_contrast_p: Optional[float] = None         # SPECIALIST: contrast-jitter probability
    da_low_res_p: Optional[float] = None          # SPECIALIST: low-resolution simulation probability (thick-slice / low-field proxy)
    da_gamma_p: Optional[float] = None            # SPECIALIST: gamma-correction probability

    # --- bias field (MRI-specific; not in nnU-Net's default pipeline) ---
    da_bias_field_p: Optional[float] = None       # SPECIALIST: bias-field probability
    da_bias_field_order: Optional[int] = None     # SPECIALIST: polynomial order of the field, ~3
    da_bias_field_coeff_range: Optional[tuple[float, float]] = None  # SPECIALIST: polynomial coefficient range

    # --- CHOICES (NOT hooks; None is legal and means "no warm start") ---
    init_weights_from: Optional[str] = None       # CHOICE: path to a checkpoint from one of OUR OWN GoAT runs
    init_weights_strict: bool = False             # CHOICE: require every model key to be present in the checkpoint


def unset_hooks(config: GoATTrainerConfigV2) -> list[str]:
    """Return the names of SPECIALIST hooks still ``None`` (i.e. not yet decided).

    Filters on :data:`SPECIALIST_HOOKS_V2` rather than every dataclass field, so the
    ``init_weights_*`` choices are never reported as missing.
    """
    return [
        f.name
        for f in fields(config)
        if f.name in SPECIALIST_HOOKS_V2 and getattr(config, f.name) is None
    ]


def assert_configured(config: GoATTrainerConfigV2) -> None:
    """Raise if any SPECIALIST hook is unset — a guard before launching a real v2 run."""
    missing = unset_hooks(config)
    if missing:
        raise ValueError(
            "Refusing to launch nnUNetTrainerGoATv2: the AI specialist must set these "
            f"# SPECIALIST hooks first: {', '.join(missing)}"
        )


# --- warm start (pure; the transfer contract is unit-testable without torch) ----------------

@dataclass(frozen=True)
class WeightTransferPlan:
    """What a checkpoint can and cannot contribute to a freshly-built model.

    ``transferable`` are the keys present in both with identical shapes — the only ones that may
    be loaded. The other three fields exist so a partial or wrong transfer is *reported*, never
    inferred from silence.
    """

    transferable: list[str]
    shape_mismatched: list[str]
    missing_in_checkpoint: list[str]
    unexpected_in_checkpoint: list[str]


def plan_weight_transfer(checkpoint_shapes: dict, model_shapes: dict) -> WeightTransferPlan:
    """Compare a checkpoint's ``{key: shape}`` against a model's and classify every key.

    Shapes are compared as tuples, so this works on ``{k: tuple(v.shape)}`` extracted from a real
    ``state_dict`` without importing torch. Results are sorted for deterministic reporting.
    """
    transferable, mismatched, missing = [], [], []
    for key, shape in model_shapes.items():
        if key not in checkpoint_shapes:
            missing.append(key)
        elif tuple(checkpoint_shapes[key]) == tuple(shape):
            transferable.append(key)
        else:
            mismatched.append(key)
    unexpected = [k for k in checkpoint_shapes if k not in model_shapes]
    return WeightTransferPlan(
        transferable=sorted(transferable),
        shape_mismatched=sorted(mismatched),
        missing_in_checkpoint=sorted(missing),
        unexpected_in_checkpoint=sorted(unexpected),
    )


def assert_transferable(plan: WeightTransferPlan, strict: bool = False) -> None:
    """Refuse a warm start that would quietly degrade into a random initialisation.

    Always raises when **nothing** transfers (the wrong checkpoint was pointed at) or when any
    shape differs (the architectures are not the same, so the transfer is not what it claims).
    With ``strict`` it additionally requires the checkpoint to cover every model tensor.
    """
    if not plan.transferable:
        raise ValueError(
            "Refusing the warm start: no tensor in the checkpoint matches this model "
            f"({len(plan.missing_in_checkpoint)} model key(s) absent, "
            f"{len(plan.unexpected_in_checkpoint)} checkpoint key(s) unused). "
            "Check init_weights_from points at a run with the same plans / configuration."
        )
    if plan.shape_mismatched:
        sample = ", ".join(plan.shape_mismatched[:3])
        raise ValueError(
            f"Refusing the warm start: {len(plan.shape_mismatched)} tensor(s) differ in shape "
            f"(e.g. {sample}). The checkpoint was produced by a different architecture."
        )
    if strict and plan.missing_in_checkpoint:
        sample = ", ".join(plan.missing_in_checkpoint[:3])
        raise ValueError(
            f"Refusing the warm start under init_weights_strict: {len(plan.missing_in_checkpoint)} "
            f"model tensor(s) are absent from the checkpoint (e.g. {sample})."
        )


def config_from_mapping(cfg: dict) -> GoATTrainerConfigV2:
    """Build a :class:`GoATTrainerConfigV2` from a train_v2-config mapping (a loaded YAML).

    Reads :data:`SPECIALIST_HOOKS_V2` plus the :data:`_CHOICE_KEYS`; list-valued tuple hooks are
    coerced from YAML lists to tuples. Missing / ``None`` keys stay ``None`` so
    :func:`unset_hooks` / :func:`assert_configured` still gate an unfilled config.
    """
    kwargs: dict = {}
    for key in SPECIALIST_HOOKS_V2 + _CHOICE_KEYS:
        value = cfg.get(key)
        if value is None:
            continue
        if key in _TUPLE_HOOKS and isinstance(value, list):
            value = tuple(value)
        kwargs[key] = value
    return GoATTrainerConfigV2(**kwargs)


def load_goat_v2_config(path: str | Path) -> GoATTrainerConfigV2:
    """Load, VALIDATE and build a :class:`GoATTrainerConfigV2` from a ``configs/train_v2.yaml``.

    Provenance-header + all-hooks validation is delegated to
    :func:`brats2026.config.assert_valid_config` with kind ``"train_v2"``, so an unfilled or
    unstamped config is refused BEFORE any training starts. The import is local so this module
    stays import-light (``brats2026.config`` imports *us* at module scope).
    """
    from ..config import assert_valid_config, load_config

    cfg = load_config(Path(path))
    assert_valid_config(cfg, "train_v2")
    return config_from_mapping(cfg)


def apply_goat_v2_config(trainer, config: GoATTrainerConfigV2) -> None:
    """Copy the directly-mappable SPECIALIST numbers onto a live ``nnUNetTrainer``.

    Sets the four standard nnU-Net attributes and MUST run before ``super().initialize()`` so the
    optimizer and dataloaders pick them up. ``batch_size`` / ``patch_size`` come from the plans,
    not here; the ``da_*`` values are consumed by :meth:`nnUNetTrainerGoATv2.get_training_transforms`.
    Duck-typed on ``trainer`` so it is unit-testable without nnU-Net installed.
    """
    assert_configured(config)
    trainer.initial_lr = config.initial_lr
    trainer.weight_decay = config.weight_decay
    trainer.num_epochs = config.num_epochs
    trainer.oversample_foreground_percent = config.oversample_foreground_percent


def install_goat_trainer_v2() -> str:
    """Drop an import shim into nnU-Net's trainer tree so ``-tr nnUNetTrainerGoATv2`` resolves.

    Writes :data:`GOAT_V2_SHIM_BODY` to :data:`GOAT_V2_SHIM_NAME`, a filename distinct from the v1
    shim so an in-flight v1 run keeps the trainer it started with. Returns the shim path;
    idempotent. Requires nnU-Net installed (import is local so the module stays import-light).
    """
    import nnunetv2

    variants = Path(nnunetv2.__file__).parent / "training" / "nnUNetTrainer" / "variants"
    variants.mkdir(parents=True, exist_ok=True)
    shim = variants / GOAT_V2_SHIM_NAME
    shim.write_text(GOAT_V2_SHIM_BODY, encoding="utf-8")
    return str(shim)


# --- bias field (pure; the one MRI corruption nnU-Net's default DA does not model) ----------

def bias_field_term_count(order: int, ndim: int = 3) -> int:
    """Number of polynomial terms of total degree ``<= order`` in ``ndim`` variables.

    ``comb(order + ndim, ndim)`` — e.g. 20 terms for the cubic 3-D field the config defaults to.
    This is exactly how many coefficients :func:`bias_field_multiplier` consumes.
    """
    from math import comb

    if order < 0:
        raise ValueError(f"order must be >= 0, got {order}")
    return comb(order + ndim, ndim)


def _bias_field_exponents(order: int, ndim: int) -> list[tuple[int, ...]]:
    """Exponent tuples of total degree ``<= order``, ordered deterministically.

    Sorted by (total degree, lexicographic) so a given coefficient vector always maps to the same
    polynomial — the field must be reproducible from a seed, not just from an object identity.
    """
    from itertools import product

    exponents = [e for e in product(range(order + 1), repeat=ndim) if sum(e) <= order]
    exponents.sort(key=lambda e: (sum(e), e))
    return exponents


def bias_field_multiplier(shape, order: int, coefficients):
    """Build a smooth, strictly-positive multiplicative bias field of ``shape``.

    Models the slow intensity inhomogeneity a real MR scanner imprints on a volume — the coil
    sensitivity roll-off that makes one side of a brain brighter than the other. nnU-Net's stock
    augmentation pipeline has noise, blur, brightness, contrast, low-res and gamma but **no**
    bias field, so this is the one genuinely new corruption v2 adds.

    The field is ``exp(mean_k(c_k * x^a_k y^b_k z^c_k))`` over normalised coordinates in
    ``[-1, 1]``:

    - the ``exp`` makes it **strictly positive**, so multiplying an image can never flip or
      annihilate an intensity;
    - all-zero coefficients give an **identity** (all-ones) field, so "off" is expressible;
    - averaging over the terms rather than summing keeps the coefficient range meaning the same
      thing at any ``order`` — a coefficient of 0.1 is ~10% log-amplitude whether the polynomial
      has 4 terms or 20. That is what lets ``da_bias_field_coeff_range`` be tuned independently
      of ``da_bias_field_order``.

    ``coefficients`` must hold at least :func:`bias_field_term_count` values (extras are ignored);
    too few raises, because a short vector would silently truncate the polynomial to a lower
    order than requested. numpy is imported locally so the module stays import-light.
    """
    import numpy as np

    shape = tuple(int(n) for n in shape)
    ndim = len(shape)
    needed = bias_field_term_count(order, ndim)
    coefficients = list(coefficients)
    if len(coefficients) < needed:
        raise ValueError(
            f"bias field of order {order} in {ndim}D needs {needed} coefficients, "
            f"got {len(coefficients)}"
        )

    # A length-1 axis has no extent to vary over; pin it at the field centre rather than at -1.
    axes = [np.linspace(-1.0, 1.0, n) if n > 1 else np.zeros(1) for n in shape]
    grids = np.meshgrid(*axes, indexing="ij")

    log_field = np.zeros(shape, dtype=np.float64)
    for coefficient, exponents in zip(coefficients, _bias_field_exponents(order, ndim)):
        term = np.ones(shape, dtype=np.float64)
        for grid, exponent in zip(grids, exponents):
            if exponent:
                term = term * grid**exponent
        log_field += coefficient * term
    log_field /= needed
    return np.exp(log_field)


def sample_bias_field_coefficients(order: int, coeff_range, rng, ndim: int = 3) -> list[float]:
    """Draw one coefficient per polynomial term, uniform in ``coeff_range``, with random signs.

    ``coeff_range`` bounds the *magnitude* (it is a SPECIALIST hook expressed as a positive
    range); the sign is randomised here so the field brightens some volumes and darkens others
    instead of always pulling the same direction. ``rng`` is any object with ``uniform`` and
    ``random`` — a seeded :class:`random.Random` in tests, numpy's generator at train time.
    """
    low, high = float(coeff_range[0]), float(coeff_range[1])
    count = bias_field_term_count(order, ndim)
    return [rng.uniform(low, high) * (1.0 if rng.random() < 0.5 else -1.0) for _ in range(count)]


# --- augmentation retuning (pure; testable against dummy transforms, no nnU-Net needed) -----

# Side length of the grid the bias field is evaluated on before trilinear upsampling to the patch.
# The field is a low-order polynomial and therefore smooth by construction, so evaluating it
# coarsely and interpolating is near-exact. Measured on this repo at order 3, coefficients 0.12,
# against a direct evaluation at a 128x160x112 patch: max relative error 0.013%, while the
# polynomial evaluation drops from ~840 ms to ~2 ms. That matters because this runs inside the
# dataloader on every augmented sample — at patch resolution it would dominate training time.
BIAS_FIELD_EVAL_GRID = 32

# Hook name -> the batchgeneratorsv2 transform classes whose probability it overrides. nnU-Net
# wraps each optional augmentation in a RandomTransform carrying `apply_probability`, so the
# override target is the WRAPPER, keyed by the class name of the transform it wraps.
#
# Several candidates per hook because the base trainer is nnUNetTrainerDA5, which uses different
# classes from the stock trainer for the same intent (additive rather than multiplicative
# brightness, a median-filter/blur choice rather than a bare blur). A hook binds to whichever
# candidate the base pipeline actually built; one that binds to none is REPORTED, not ignored.
DA_PROBABILITY_HOOKS: dict[str, tuple[str, ...]] = {
    "da_noise_p": ("GaussianNoiseTransform",),
    "da_blur_p": ("GaussianBlurTransform", "MedianFilterTransform"),
    "da_brightness_p": ("MultiplicativeBrightnessTransform", "BrightnessAdditiveTransform"),
    "da_contrast_p": ("ContrastTransform",),
    "da_low_res_p": ("SimulateLowResolutionTransform",),
    "da_gamma_p": ("GammaTransform",),
    "da_bias_field_p": ("BiasFieldTransform",),
}


def _walk_transforms(node):
    """Yield every transform in a (possibly nested) batchgeneratorsv2 transform tree.

    Duck-typed on a ``transforms`` list (ComposeTransforms) and a ``transform`` attribute
    (RandomTransform), so the walk works on real nnU-Net objects and on test doubles alike.
    """
    yield node
    children = getattr(node, "transforms", None)
    if isinstance(children, (list, tuple)):
        for child in children:
            yield from _walk_transforms(child)
    wrapped = getattr(node, "transform", None)
    if wrapped is not None:
        yield from _walk_transforms(wrapped)


def retune_augmentation(transforms, config: GoATTrainerConfigV2) -> dict[str, object]:
    """Rewrite nnU-Net's default augmentation strengths in place from the SPECIALIST hooks.

    Two distinct edits, both **overrides** rather than additions (a probability hook replaces
    nnU-Net's default probability, it does not compose with it):

    - every ``da_*_p`` hook sets ``apply_probability`` on the ``RandomTransform`` wrapping the
      class named in :data:`DA_PROBABILITY_HOOKS`;
    - ``da_scale_range`` replaces ``SpatialTransform.scaling``, which is what widens the range of
      brain sizes the model sees (paediatric brains and sub-cm metastases are the motivating
      cases, and PED has no training data at all).

    Returns a report of what was actually retuned so :meth:`nnUNetTrainerGoATv2.get_training_
    transforms` can log it. A hook that matched nothing is reported as missing rather than
    silently ignored — a renamed transform class upstream must not quietly disable an override.
    """
    report: dict[str, object] = {"retuned": {}, "missing": []}
    by_class = {name: hook for hook, names in DA_PROBABILITY_HOOKS.items() for name in names}
    matched: set[str] = set()

    for node in _walk_transforms(transforms):
        wrapped = getattr(node, "transform", None)
        if wrapped is not None and hasattr(node, "apply_probability"):
            # DA5 wraps alternatives in a OneOfTransform, so the RandomTransform's direct child is
            # the group, not the augmentation. Look one level into any group before giving up.
            candidates = [wrapped]
            group = getattr(wrapped, "transforms", None)
            if isinstance(group, (list, tuple)):
                candidates.extend(group)
            # nnU-Net ships TWO GammaTransforms: an INVERTED pass (p_invert_image=1, stock 0.10)
            # and a plain one (p_invert_image=0, stock 0.30). da_gamma_p names the plain one only.
            # Matching on class name alone would raise the inverted pass to the same value —
            # a 4.5x jump nobody asked for, invisible in the logs, and it would silently make the
            # v1-vs-v2 delta a two-variable change.
            candidates = [
                c for c in candidates
                if not (type(c).__name__ == "GammaTransform" and getattr(c, "p_invert_image", 0))
            ]
            hook = next((by_class[type(c).__name__] for c in candidates
                         if type(c).__name__ in by_class), None)
            if hook is not None:
                value = getattr(config, hook)
                if value is not None:
                    node.apply_probability = float(value)
                    report["retuned"][hook] = float(value)  # type: ignore[index]
                    matched.add(hook)
        if type(node).__name__ == "SpatialTransform" and config.da_scale_range is not None:
            node.scaling = tuple(config.da_scale_range)
            report["retuned"]["da_scale_range"] = tuple(config.da_scale_range)  # type: ignore[index]
            matched.add("da_scale_range")

    for hook in list(DA_PROBABILITY_HOOKS) + ["da_scale_range"]:
        if getattr(config, hook) is not None and hook not in matched:
            report["missing"].append(hook)  # type: ignore[union-attr]
    return report


# --- warm start (torch) ---------------------------------------------------------------------

def load_warm_start_weights(model, checkpoint_path: str | Path, strict: bool = False):
    """Seed ``model`` from one of OUR OWN converged GoAT checkpoints, or refuse loudly.

    The transfer is planned on shapes first (:func:`plan_weight_transfer`) and gated by
    :func:`assert_transferable`, so the failure mode that costs GPU-days — pointing at a
    checkpoint from different plans, getting a near-empty load, and training from what is
    effectively a random init without noticing — raises instead of proceeding. Only the tensors
    the plan marked ``transferable`` are copied; nothing is loaded partially by shape coercion.

    Returns the :class:`WeightTransferPlan` so the caller can log the coverage. torch is imported
    locally so this module still imports in a bare environment.
    """
    import torch

    checkpoint = torch.load(str(checkpoint_path), map_location="cpu", weights_only=False)
    # nnU-Net writes {'network_weights': state_dict, ...}; a bare state_dict is also accepted.
    state = checkpoint
    for key in ("network_weights", "state_dict", "model_state_dict"):
        if isinstance(checkpoint, dict) and key in checkpoint:
            state = checkpoint[key]
            break
    if not isinstance(state, dict):
        raise ValueError(f"{checkpoint_path} did not contain a state_dict-like mapping")

    model_state = model.state_dict()
    plan = plan_weight_transfer(
        {k: tuple(v.shape) for k, v in state.items() if hasattr(v, "shape")},
        {k: tuple(v.shape) for k, v in model_state.items()},
    )
    assert_transferable(plan, strict=strict)
    model.load_state_dict({k: state[k] for k in plan.transferable}, strict=False)
    return plan


def resolve_v2_config(config: GoATTrainerConfigV2) -> GoATTrainerConfigV2:
    """Return ``config`` if already filled, else load the one named by the v2 env var.

    nnU-Net resolves a trainer by NAME and cannot be handed an object, so a filled
    ``configs/train_v2.yaml`` reaches the trainer through
    :data:`GOAT_V2_TRAIN_CONFIG_ENV`. Split out of the trainer class so the
    resolution order (class attribute wins, env var is the fallback) is testable without
    nnU-Net installed. Raises via :func:`assert_configured` if neither source fills the hooks.
    """
    if unset_hooks(config):
        env_path = os.environ.get(GOAT_V2_TRAIN_CONFIG_ENV)
        if env_path:
            config = load_goat_v2_config(env_path)
    assert_configured(config)
    return config


# --- concrete trainer (only when nnU-Net is available) --------------------------------------
#
# NOTE ON VERIFICATION: everything below runs ONLY where nnunetv2 + batchgeneratorsv2 are
# installed, i.e. the HPC — never in CI and never on the dev laptop. The pure functions above are
# unit-tested; the glue here is not, so `docs/RUN_HPC_V2.md` carries a mandatory transform
# smoke-test to run BEFORE committing GPU time. Treat the batchgeneratorsv2 API use below as
# unverified against an installed copy until that smoke-test passes.
try:  # pragma: no cover - exercised only in a full training environment
    from batchgeneratorsv2.transforms.base.basic_transform import ImageOnlyTransform
    from batchgeneratorsv2.transforms.utils.random import RandomTransform
    from nnunetv2.training.nnUNetTrainer.variants.data_augmentation.nnUNetTrainerDA5 import (
        nnUNetTrainerDA5,
    )

    class BiasFieldTransform(ImageOnlyTransform):
        """Multiply an image by a smooth, spatially-varying random gain field.

        **What this actually is, stated honestly.** nnU-Net z-score-normalises in preprocessing,
        so the patches this sees are ~N(0,1) and contain negative values. Multiplying those by a
        positive field does not "brighten" a region the way a bias field brightens raw MR signal —
        it scales the deviation from the mean, amplifying contrast where the field is >1 and
        compressing it where it is <1. So this is a **spatial generalisation of nnU-Net's global
        MultiplicativeBrightnessTransform**, not a literal B1/B0 inhomogeneity model. That is
        still the right augmentation to add — nnU-Net has *no* spatially-varying intensity
        transform at all, and cross-scanner intensity variation is spatial — but the paper must
        describe it this way rather than claiming a physical bias-field simulation.

        **Cost.** The field is evaluated on a coarse grid and trilinearly upsampled. Evaluating
        the polynomial directly at a 128x160x112 patch costs ~680 ms, which at this transform's
        probability would add hours per fold inside the dataloader. The field is a low-order
        polynomial and therefore smooth by construction, so coarse evaluation is near-exact —
        see :data:`BIAS_FIELD_EVAL_GRID`.

        Image-only by construction: a multiplicative intensity field must never touch the
        segmentation, and inheriting ``ImageOnlyTransform`` makes that structural.
        """

        def __init__(self, order: int, coeff_range):
            super().__init__()
            self.order = int(order)
            self.coeff_range = tuple(coeff_range)

        def get_parameters(self, **data_dict) -> dict:
            return {}

        def _apply_to_image(self, img, **params):
            import numpy as np
            import torch

            spatial = tuple(int(n) for n in img.shape[-3:])
            coarse = tuple(min(n, BIAS_FIELD_EVAL_GRID) for n in spatial)
            # Draw from numpy's GLOBAL RNG rather than a private Generator: nnU-Net seeds each
            # dataloader worker's global numpy state, so this inherits the run's seeding exactly
            # like nnU-Net's own transforms. A private default_rng() would ignore the config seed
            # and make the run irreproducible.
            coefficients = sample_bias_field_coefficients(self.order, self.coeff_range, np.random)
            field = bias_field_multiplier(coarse, self.order, coefficients)
            tensor = torch.as_tensor(field, dtype=img.dtype, device=img.device)[None, None]
            if coarse != spatial:
                # align_corners=True matches bias_field_multiplier's own [-1, 1] endpoint grid.
                tensor = torch.nn.functional.interpolate(
                    tensor, size=spatial, mode="trilinear", align_corners=True
                )
            return img * tensor[0, 0]

    class nnUNetTrainerGoATv2(nnUNetTrainerDA5):
        """Warm-started GoAT trainer built on nnU-Net's own aggressive-augmentation variant.

        **Why DA5 is the base.** DKFZ already ships ``nnUNetTrainerDA5`` ("more data
        augmentation"), which includes ``BrightnessGradientAdditiveTransform`` and
        ``LocalGammaTransform`` at p=0.3 — spatially-varying intensity corruption, the same intent
        as a bias field, already validated in DKFZ's own challenge entries. Inheriting it means v2
        gets a proven augmentation pipeline rather than a hand-tuned one, and DA5's philosophy
        (more KINDS of corruption at wider ranges) costs less small-lesion sensitivity than
        raising every probability uniformly would — which matters given our ET weakness.

        What this adds on top, none of which DA5 has: a **warm start** from a converged fold of
        our own GoAT run (~150 epochs instead of 1000), a **config gate** binding every number to
        a validated, fingerprinted :class:`GoATTrainerConfigV2`, and **retuning hooks** over DA5's
        defaults that report loudly when one fails to bind.
        """

        # Class-level on purpose: nnU-Net declares get_training_transforms a @staticmethod, which
        # therefore cannot read `self`. initialize() publishes the resolved config here so the
        # transform builder can reach it. Set per-process, never shared across runs.
        goat_config: GoATTrainerConfigV2 = GoATTrainerConfigV2()

        def initialize(self):  # noqa: D401
            cfg = resolve_v2_config(self.goat_config)
            type(self).goat_config = cfg          # publish BEFORE transforms are built
            self.goat_config = cfg
            apply_goat_v2_config(self, cfg)       # lr / wd / epochs / oversample BEFORE super()
            super().initialize()
            if cfg.init_weights_from:
                plan = load_warm_start_weights(
                    self.network, cfg.init_weights_from, strict=cfg.init_weights_strict
                )
                self.print_to_log_file(
                    f"GoATv2 warm start from {cfg.init_weights_from}: "
                    f"{len(plan.transferable)} tensor(s) transferred, "
                    f"{len(plan.missing_in_checkpoint)} absent from the checkpoint."
                )
            else:
                self.print_to_log_file("GoATv2: no init_weights_from set — training from scratch.")

        @staticmethod
        def get_training_transforms(*args, **kwargs):
            """nnU-Net's training transforms, plus a bias field, retuned from the config.

            Deliberately built on top of the parent's pipeline rather than replacing it: v2's
            thesis is that nnU-Net's augmentation is *too weak* for cross-cohort generalisation,
            not that it is wrong. ``*args/**kwargs`` passthrough keeps this working across
            nnU-Net versions that add parameters to the signature.
            """
            transforms = nnUNetTrainerDA5.get_training_transforms(*args, **kwargs)
            cfg = nnUNetTrainerGoATv2.goat_config

            if cfg.da_bias_field_order is not None and cfg.da_bias_field_coeff_range is not None:
                bias = RandomTransform(
                    BiasFieldTransform(cfg.da_bias_field_order, cfg.da_bias_field_coeff_range),
                    apply_probability=float(cfg.da_bias_field_p or 0.0),
                )
                # Appended before retuning so retune_augmentation sets its probability like any
                # other hook, and so a missing da_bias_field_p is reported rather than assumed.
                transforms.transforms.append(bias)

            report = retune_augmentation(transforms, cfg)
            print(f"[GoATv2] augmentation retuned: {report['retuned']}")
            if report["missing"]:
                # Loud, not fatal: a renamed upstream transform silently disabling an override
                # would make the v1-vs-v2 comparison meaningless without anything failing.
                print(f"[GoATv2] WARNING: hooks that matched no transform: {report['missing']}")
            return transforms

except ImportError:  # nnU-Net not installed (e.g. CI / planning env)
    BiasFieldTransform = None  # type: ignore[assignment,misc]
    nnUNetTrainerGoATv2 = None  # type: ignore[assignment,misc]
